// Generated by CoffeeScript 1.10.0
(function() {
  window.app.odse.TransactioNodeListManager = (function() {
    function TransactioNodeListManager() {}

    TransactioNodeListManager.sort = function(transactionNodeList) {
      var sortedTransactionNodeList;
      sortedTransactionNodeList = transactionNodeList.sort(function(left, right) {
        return left.createdTimeStamp - right.createdTimeStamp;
      });
      return sortedTransactionNodeList;
    };

    return TransactioNodeListManager;

  })();

  window.app.odse.TransactioNodeListManager = window.app.odse.TransactioNodeListManager;

}).call(this);
